### ISSUE TITLE
Panic with Dataset

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#163]
I was trying out latest main branch 8f168b7ad096eed54718404765f26bdb0ce2cccf and using examples/datasets/k8s-instructions.yaml

```
2023-08-02T05:12:02Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference       {"controller": "dataset", "controllerGroup": "substratus.ai", "controllerKind": "Dataset", "Dataset": {"name":"k8s-instructions","namespace":"default"}, "namespace": "default", "name": "k8s-instructions", "reconcileID": "ce0ac48d-3c9c-4a41-819e-8
391ee5fdba0"}                                                                                                                  
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                            
        panic: runtime error: invalid memory address or nil pointer dereference                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x159e2ce]                                                       
                                                                                                                               
goroutine 272 [running]:                                       
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                     
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:119 +0x1fa                    
panic({0x171e7e0, 0x27c7320})                                  
        /usr/local/go/src/runtime/panic.go:884 +0x212                                                                          
github.com/substratusai/substratus/internal/controller.(*ContainerImageReconciler).ReconcileContainerImage(0xc000382230, {0x1bb
f1f8, 0xc000a18810}, {0x1bd4998, 0xc000487040})                                                                                
        /workspace/internal/controller/container_reconciler.go:168 +0xd8e                                                      
github.com/substratusai/substratus/internal/controller.(*DatasetReconciler).Reconcile(0xc0007eaec0, {0x1bbf1f8, 0xc000a18810}, 
{{{0xc000667316?, 0x10?}, {0xc000667320?, 0x40da67?}}})
        /workspace/internal/controller/dataset_controller.go:45 +0x296                                                         
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1bbf1f8?, {0x1bbf1f8?, 0xc000a18810?}, {{{0xc000667316?, 0x169a380?}, {0xc000667320?, 0x0?}}})                                                                               
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122 +0xc8                     
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005074a0, {0x1bbf150, 0xc00078a780}, 
{0x177b580?, 0xc00027c300?})                 
```

**Comment by samos123** [comment]
confirmed that it's now all working after releasing v0.7.0-alpha
